version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8072:80" # Map port 8081 on host to port 80 in the container for PHP 7.2
      - "8081:80" # Map port 8072 on host to port 80 in the container for PHP 8.1
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./projects:/var/www
      # - ./projects/project1:/var/www/project1
      # - ./projects/project2:/var/www/project2

  php72:
    image: php:7.2-fpm
    volumes:
      - ./projects/project1:/var/www/project1

  php81:
    image: php:8.1-fpm
    volumes:
      - ./projects/project2:/var/www/project2
