# Dockerfile for project1
FROM php:7.2-fpm

# Copy project code
COPY . /var/www/project1

# Optional: install extensions if needed
# RUN docker-php-ext-install mysqli pdo pdo_mysql

WORKDIR /var/www/project1
EXPOSE 9000
