name: Build Docker Images

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:   # tombol Run workflow muncul di UI

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build project1
      - name: Build project1 Docker image
        run: |
          docker build -t project1:latest -f projects/project1/Dockerfile projects/project1
          docker save project1:latest -o project1_latest.tar

      - name: Upload project1 Docker image
        uses: actions/upload-artifact@v4
        with:
          name: project1-image
          path: project1_latest.tar

      # Build project2
      - name: Build project2 Docker image
        run: |
          docker build -t project2:latest -f projects/project2/Dockerfile projects/project2
          docker save project2:latest -o project2_latest.tar

      - name: Upload project2 Docker image
        uses: actions/upload-artifact@v4
        with:
          name: project2-image
          path: project2_latest.tar
