name: Build Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:   # tombol Run workflow muncul di UI

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose
        run: docker compose config

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Save Docker image as tar
        run: docker save myapp:latest -o myapp_latest.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-image
          path: myapp_latest.tar
